import type { ChapterMember } from '@/types/seating';

export const CHAPTER_MEMBER_DIRECTORY: ChapterMember[] = [
  { name: '馬廷軒', adminGroup: '第 1 組', roles: ['導師', '執事', '邀賓英雄'] },
  { name: '洪宗宏', adminGroup: '第 1 組', roles: ['導師'] },
  { name: '黃佳琪', adminGroup: '第 1 組', roles: ['邀賓英雄'] },
  { name: '叢晧日', adminGroup: '第 1 組', roles: ['執事'] },
  { name: '吳振綱', adminGroup: '第 1 組', roles: ['會員', '音控'] },
  { name: '郭子郁', adminGroup: '第 1 組', roles: ['會員', '值日生'] },
  { name: '蘇子茵', adminGroup: '第 2 組', roles: ['導師', '執事', '邀賓英雄'] },
  { name: '梁文齡', adminGroup: '第 2 組', roles: ['導師'] },
  { name: '黃柔涵', adminGroup: '第 2 組', roles: ['邀賓英雄'] },
  { name: '田謦蓉', adminGroup: '第 2 組', roles: ['執事'] },
  { name: '王致崴', adminGroup: '第 2 組', roles: ['會員'] },
  { name: '王建豐', adminGroup: '第 2 組', roles: ['會員'] },
  { name: '林家均', adminGroup: '第 3 組', roles: ['導師', '執事', '邀賓英雄'] },
  { name: '林子晏', adminGroup: '第 3 組', roles: ['會員'] },
  { name: '邱孟婷', adminGroup: '第 3 組', roles: ['執事', '邀賓英雄'] },
  { name: '林道元', adminGroup: '第 3 組', roles: ['導師'] },
  { name: '陳宜均', adminGroup: '第 3 組', roles: ['會員'] },
  { name: '劉庭羽', adminGroup: '第 3 組', roles: ['會員'] },
  { name: '黃嘉琪', adminGroup: '第 3 組', roles: ['會員'] },
  { name: '葉心琳', adminGroup: '第 3 組', roles: ['會員'] },
  { name: '邱柏瀚', adminGroup: '第 4 組', roles: ['導師', '執事', '邀賓英雄'] },
  { name: '戴嘉慧', adminGroup: '第 4 組', roles: ['執事', '邀賓英雄', '財務秘書'] },
  { name: '王柏詠', adminGroup: '第 4 組', roles: ['導師'] },
  { name: '陳泓睿', adminGroup: '第 4 組', roles: ['會員'] },
  { name: '簡偉志', adminGroup: '第 4 組', roles: ['會員'] },
  { name: '戴宇星', adminGroup: '第 4 組', roles: ['會員'] },
  { name: '古又帆', adminGroup: '第 5 組', roles: ['執事', '邀賓英雄', '主席'] },
  { name: '黎士銓', adminGroup: '第 5 組', roles: ['導師', '執事'] },
  { name: '張媁淇', adminGroup: '第 5 組', roles: ['執事', '活動協調'] },
  { name: '陳志誠', adminGroup: '第 5 組', roles: ['會員'] },
  { name: '陳俊鳴', adminGroup: '第 5 組', roles: ['會員'] },
  { name: '黃子宜', adminGroup: '第 6 組', roles: ['執事', '邀賓英雄', '副主席'] },
  { name: '蘇冠霖', adminGroup: '第 6 組', roles: ['導師', '執事'] },
  { name: '林育群', adminGroup: '第 6 組', roles: ['執事', '教育協調'] },
  { name: '林塏秢', adminGroup: '第 6 組', roles: ['會員'], note: '代理' },
  { name: '程睿紳', adminGroup: '第 6 組', roles: ['會員'], note: '代理' },
];

export const CHAPTER_MEMBER_NAMES = CHAPTER_MEMBER_DIRECTORY.map((member) => member.name);
